### PR TITLE
Support for stm32f1 medium density devices

### PR DESCRIPTION
**Pull request by Koehlerorum**
- Added support for stm32f1 medium density device.
- Added basic makefile to easy up Mac OS X and Linux builds
- Fixed few compiler warnings
- Updated copyright info according to the made changes.

### CODE REVIEW

**Comment by wcontello** [comment]
I think the while loop has is missing the increment on the pointer too the list of IDs

**Comment by wcontello** [comment]
Any chance of getting  these changes merged in?  I would like to attempt to update for use with an STM32F0 part (ID 0448)

**Comment by bogdanm** [comment]
Thanks for your contribution, and apologies for not noticing this earlier!

**Comment by wcontello** [comment]
THANKS!  Has anyone used this with an STM32F072?  I am curious because I have not been able to get it to work.  I was trying with what was checked in before your last check in and post.  I will try this tomorrow.

**Comment by bogdanm** [comment]
I've only ever used it for STM32F1 CPUs, sorry.

**Comment by Koehlerorum** [comment]
Thanks @wcontello for pointing out the missing increment. Created a pull request to fix the issue.

**Pull request merged**
